"""
tests/conftest.py

Shared pytest fixtures for the Billboard Cultural Mood Analysis test suite.

Fixtures provided:
    project_config        — real ProjectConfig loaded from config/project_config.yaml
    tmp_config            — ProjectConfig with tmp paths overriding output dirs
    pipeline_workspace    — tmp_path with full required directory structure
    sample_songs_df       — 5-song fixture DataFrame (lyrics_cleaned schema)
    sample_sentiment_df   — 5-song sentiment scores fixture
    sample_emotion_df     — 5-song emotion classification fixture
    sample_themes_df      — 5-song themes fixture
    sample_chorus_df      — 5-song chorus extraction fixture
    sample_layer4_df      — 5-song master merged fixture (layer4 schema)
    sample_cmi_df         — 7-decade CMI aggregate fixture
    mock_openai_client    — deterministic mock returning valid Jungian responses
    lyrics_csv_path       — writes sample_songs_df to tmp workspace, returns path
    sentiment_csv_path    — writes sample_sentiment_df to tmp workspace, returns path

All fixture DataFrames use song_ids generated by make_song_id() to guarantee
they are valid 16-char hex values that pass schema validation.

FIXTURE_SONGS defines the canonical 5-song set used across all tests.
Song IDs are deterministic — the same artist/title/year always produces
the same song_id, making fixtures reproducible across test runs.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Generator
from unittest.mock import MagicMock, patch

import numpy as np
import pandas as pd
import pytest

from src.pipeline.config_loader import ProjectConfig, load_config
from src.pipeline.schemas import VALID_DECADE_LABELS
from src.utils.identifiers import make_song_id

# ── Canonical Fixture Songs ───────────────────────────────────────────────────

FIXTURE_SONGS = [
    {"artist": "The Beatles", "title": "Hey Jude", "year": 1968, "decade": "1960s*"},
    {
        "artist": "Michael Jackson",
        "title": "Billie Jean",
        "year": 1983,
        "decade": "1980s",
    },
    {
        "artist": "Nirvana",
        "title": "Smells Like Teen Spirit",
        "year": 1991,
        "decade": "1990s",
    },
    {"artist": "Beyonce", "title": "Crazy in Love", "year": 2003, "decade": "2000s"},
    {"artist": "Billie Eilish", "title": "Bad Guy", "year": 2019, "decade": "2010s"},
]

# Pre-compute deterministic song_ids
FIXTURE_SONG_IDS = [
    make_song_id(s["artist"], s["title"], s["year"]) for s in FIXTURE_SONGS
]

# Sample lyrics for fixture songs (short but sufficient for NLP testing)
FIXTURE_LYRICS = [
    "Hey Jude don't make it bad take a sad song and make it better",
    "She was more like a beauty queen from a movie scene I said don't mind but what do you mean",
    "Load up on guns bring your friends it's fun to lose and to pretend",
    "Crazy in love got me looking so crazy right now your love got me looking so crazy right now",
    "I'm that bad type make your mama sad type might seduce your dad type",
]


# ── Config Fixtures ───────────────────────────────────────────────────────────


@pytest.fixture(scope="session")
def project_config() -> ProjectConfig:
    """
    Load the real ProjectConfig from config/project_config.yaml.

    Session-scoped — loaded once per test session.
    """
    return load_config()


@pytest.fixture(scope="function")
def tmp_config(tmp_path: Path, project_config: ProjectConfig) -> ProjectConfig:
    """
    Return a ProjectConfig copy with output paths overridden to tmp_path.

    Function-scoped — each test gets a fresh config pointing to isolated
    tmp directories, preventing test artifacts from polluting the real
    data/ and outputs/ directories.
    """
    config = project_config.model_copy(deep=True)
    config.output.output_dir = str(tmp_path / "outputs")
    config.lyrics.cache_dir = str(tmp_path / "cache" / "lyrics")
    return config


# ── Workspace Fixture ─────────────────────────────────────────────────────────


@pytest.fixture(scope="function")
def pipeline_workspace(tmp_path: Path) -> Path:
    """
    Create a complete pipeline directory structure under tmp_path.

    Creates:
        tmp_path/data/raw/
        tmp_path/data/processed/
        tmp_path/data/analysis/
        tmp_path/outputs/visualizations/
        tmp_path/outputs/reports/
        tmp_path/outputs/logs/
        tmp_path/cache/lyrics/

    Returns:
        tmp_path root — all pipeline modules should use this as the
        working directory base during tests.
    """
    dirs = [
        "data/raw",
        "data/processed",
        "data/analysis",
        "outputs/visualizations",
        "outputs/reports",
        "outputs/logs",
        "cache/lyrics",
    ]
    for d in dirs:
        (tmp_path / d).mkdir(parents=True, exist_ok=True)

    return tmp_path


# ── DataFrame Fixtures ────────────────────────────────────────────────────────


@pytest.fixture(scope="session")
def sample_songs_df() -> pd.DataFrame:
    """
    5-song fixture DataFrame matching the cleaned_schema.

    Represents the output of lyrics_cleaned.csv (Stage 3).
    All required columns are present with valid values.
    """
    rows = []
    for i, song in enumerate(FIXTURE_SONGS):
        rows.append(
            {
                "song_id": FIXTURE_SONG_IDS[i],
                "song_title": song["title"],
                "artist": song["artist"],
                "year": song["year"],
                "decade": song["decade"],
                "lyrics_clean": FIXTURE_LYRICS[i],
                "lyrics_verse_only": FIXTURE_LYRICS[i],
                "token_count": len(FIXTURE_LYRICS[i].split()),
                "lyrics_quality": "full",
                "narrative_perspective": "first_person",
                "has_section_tags": False,
                "section_count": 0,
            }
        )
    return pd.DataFrame(rows)


@pytest.fixture(scope="session")
def sample_sentiment_df() -> pd.DataFrame:
    """
    5-song fixture DataFrame matching layer2_sentiment_schema.

    Represents the output of layer2_sentiment.csv (Stage 5).
    Includes one song with a negative score to test distribution logic.
    """
    sentiment_scores = [0.45, -0.15, -0.62, 0.78, -0.31]
    energy_levels = [3, 2, 1, 5, 2]

    return pd.DataFrame(
        {
            "song_id": FIXTURE_SONG_IDS,
            "sentiment_score": sentiment_scores,
            "energy_level": pd.array(energy_levels, dtype=pd.Int64Dtype()),
        }
    )


@pytest.fixture(scope="session")
def sample_emotion_df() -> pd.DataFrame:
    """
    5-song fixture DataFrame matching layer2_emotion_schema.

    Represents partial output of layer2_emotion.csv (Stage 6).
    Two songs have chorus data; three do not (chorus_detected=False).
    """
    return pd.DataFrame(
        {
            "song_id": FIXTURE_SONG_IDS,
            "emotional_tone": ["joy", "fear", "anger", "joy", "neutral"],
            "chorus_sentiment_score": [0.40, None, None, 0.85, None],
            "chorus_emotional_tone": ["joy", None, None, "joy", None],
        }
    )


@pytest.fixture(scope="session")
def sample_themes_df() -> pd.DataFrame:
    """
    5-song fixture DataFrame matching layer2_themes_schema.

    Represents output of layer2_themes.csv (Stage 7).
    Themes are pipe-delimited strings from the 12-class taxonomy.
    """
    return pd.DataFrame(
        {
            "song_id": FIXTURE_SONG_IDS,
            "themes": [
                "love|nostalgia",
                "identity|fear",
                "rebellion|struggle",
                "love|empowerment",
                "identity|self_reflection",
            ],
        }
    )


@pytest.fixture(scope="session")
def sample_chorus_df() -> pd.DataFrame:
    """
    5-song fixture DataFrame matching chorus_schema.

    Represents output of chorus_extracted.csv (Stage 4).
    Two songs have detected choruses; three fall back to "none".
    """
    return pd.DataFrame(
        {
            "song_id": FIXTURE_SONG_IDS,
            "chorus_detected": [True, False, False, True, False],
            "chorus_method": ["tag", "none", "none", "repetition", "none"],
            "chorus_text": [
                "Hey Jude don't make it bad",
                None,
                None,
                "Crazy in love got me looking so crazy",
                None,
            ],
            "chorus_token_count": [6, 0, 0, 8, 0],
        }
    )


@pytest.fixture(scope="session")
def sample_layer4_df(
    sample_songs_df: pd.DataFrame,
    sample_sentiment_df: pd.DataFrame,
    sample_emotion_df: pd.DataFrame,
    sample_themes_df: pd.DataFrame,
    sample_chorus_df: pd.DataFrame,
) -> pd.DataFrame:
    """
    5-song master merged fixture matching layer4_schema.

    Represents the output of layer2_full_analysis.csv (Stage 8).
    Built by merging all layer fixtures — mirrors what contrast_metrics
    produces in a real run.
    """
    df = sample_songs_df.merge(sample_sentiment_df, on="song_id", how="left")
    df = df.merge(sample_emotion_df, on="song_id", how="left")
    df = df.merge(sample_themes_df, on="song_id", how="left")
    df = df.merge(sample_chorus_df, on="song_id", how="left")

    # Add Layer 4 contrast columns
    df["contrast_sentiment_index"] = [0.05, None, None, -0.07, None]
    df["energy_shift"] = ["stable", None, None, "increase", None]
    df["theme_shift"] = ["none", None, None, "none", None]

    # Ensure correct types
    df["chorus_detected"] = df["chorus_detected"].fillna(False).astype(bool)
    df["chorus_method"] = df["chorus_method"].fillna("none")
    df["section_count"] = df["section_count"].fillna(0).astype(int)
    df["has_section_tags"] = df["has_section_tags"].fillna(False).astype(bool)

    return df


@pytest.fixture(scope="session")
def sample_cmi_df() -> pd.DataFrame:
    """
    7-decade fixture DataFrame matching decade_cmi_schema.

    Represents the output of decade_cmi.csv (Stage 10).
    One decade has null CMI values to test null-handling in charts.
    """
    return pd.DataFrame(
        {
            "decade_label": VALID_DECADE_LABELS,
            "song_count": [120, 98, 105, 112, 108, 115, 42],
            "scored_count": [115, 94, 100, 108, 103, 110, 40],
            "CMI_sentiment": [0.12, 0.08, -0.05, 0.15, 0.22, 0.18, None],
            "CMI_energy": [2.8, 3.1, 3.4, 3.2, 3.0, 3.5, None],
            "dominant_emotion": ["joy", "joy", "anger", "joy", "neutral", "joy", None],
            "dominant_jung_stage": [
                "persona",
                "shadow",
                "shadow",
                "integration",
                "persona",
                "anima_animus",
                None,
            ],
            "top_themes": [
                "love|nostalgia",
                "love|struggle",
                "rebellion|identity",
                "love|wealth_success",
                "love|party_celebration",
                "love|empowerment",
                None,
            ],
            "top_resonance_songs": [
                "Hey Jude",
                "Stayin Alive",
                "Billie Jean",
                "Smells Like Teen Spirit",
                "Crazy in Love",
                "Bad Romance",
                None,
            ],
        }
    )


# ── CSV Path Fixtures ─────────────────────────────────────────────────────────


@pytest.fixture(scope="function")
def lyrics_csv_path(
    pipeline_workspace: Path,
    sample_songs_df: pd.DataFrame,
) -> Path:
    """
    Write sample_songs_df to pipeline_workspace/data/processed/lyrics_cleaned.csv.

    Returns the Path to the written file.
    Used by tests that invoke run() functions directly.
    """
    path = pipeline_workspace / "data" / "processed" / "lyrics_cleaned.csv"
    sample_songs_df.to_csv(path, index=False)
    return path


@pytest.fixture(scope="function")
def sentiment_csv_path(
    pipeline_workspace: Path,
    sample_sentiment_df: pd.DataFrame,
) -> Path:
    """
    Write sample_sentiment_df to pipeline_workspace/data/analysis/layer2_sentiment.csv.

    Returns the Path to the written file.
    Used by contrast_metrics tests that need sentiment input.
    """
    path = pipeline_workspace / "data" / "analysis" / "layer2_sentiment.csv"
    sample_sentiment_df.to_csv(path, index=False)
    return path


# ── Mock OpenAI Client ────────────────────────────────────────────────────────


def _make_jungian_response(song_ids: list[str]) -> MagicMock:
    """
    Build a mock OpenAI ChatCompletion response containing deterministic
    Jungian classifications for the given song_ids.

    Each song receives:
        jung_stage:          "persona"
        psychological_theme: "social conformity and identity formation"
        development_score:   4

    Args:
        song_ids: List of song_id strings to include in the response.

    Returns:
        MagicMock mimicking an openai.types.chat.ChatCompletion object.
    """
    records = [
        {
            "song_id": sid,
            "jung_stage": "persona",
            "psychological_theme": "social conformity and identity formation",
            "development_score": 4,
        }
        for sid in song_ids
    ]

    content = json.dumps(records)
    mock_msg = MagicMock()
    mock_msg.content = content

    mock_choice = MagicMock()
    mock_choice.message = mock_msg

    mock_response = MagicMock()
    mock_response.choices = [mock_choice]

    return mock_response


@pytest.fixture(scope="function")
def mock_openai_client() -> MagicMock:
    """
    Return a mock OpenAI client whose chat.completions.create() method
    returns deterministic Jungian classifications without making API calls.

    Usage in tests:
        def test_jungian(mock_openai_client, sample_layer4_df):
            with patch('src.psychology.jungian_scorer._get_client',
                       return_value=mock_openai_client):
                result = run(config)

    The mock inspects the prompt to extract song_ids and generates
    a matching response — ensuring the validator has correct IDs to check.
    """
    client = MagicMock()

    def _create_side_effect(*args, **kwargs):
        # Extract song_ids from the prompt content
        messages = kwargs.get("messages", [])
        prompt = " ".join(
            m.get("content", "") if isinstance(m, dict) else str(m) for m in messages
        )
        # Return deterministic responses for fixture song_ids
        matching_ids = [sid for sid in FIXTURE_SONG_IDS if sid in prompt]
        if not matching_ids:
            matching_ids = [FIXTURE_SONG_IDS[0]]

        return _make_jungian_response(matching_ids)

    client.chat.completions.create.side_effect = _create_side_effect
    return client


# ── Sentinel Fixture ──────────────────────────────────────────────────────────


@pytest.fixture(scope="function")
def write_sentiment_sentinel(
    pipeline_workspace: Path,
    project_config: ProjectConfig,
) -> Path:
    """
    Write a valid .sentiment_complete sentinel to pipeline_workspace.

    Useful for testing
    """
    from src.pipeline.config_loader import config_hash as compute_hash

    sentinel_path = pipeline_workspace / "data" / "analysis" / ".sentiment_complete"
    sentinel_path.parent.mkdir(parents=True, exist_ok=True)

    payload = {
        "stage": "SENTIMENT_SCORING",
        "completed_at": "2026-03-20T00:00:00+00:00",
        "config_hash": compute_hash(project_config),
        "scored": 5,
        "total": 5,
    }
    sentinel_path.write_text(json.dumps(payload), encoding="utf-8")
    return sentinel_path
